# Site settings
title: Old dog, new tricks
header-img: img/home-bg.png
email: jentx123@hotmail.com
copyright_name: jenhaddock
description: > # this means to ignore newlines until "baseurl:"
  A former COBOL developer learning Javascript and Ruby
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jenhaddock
learn_profile: jenhaddock
email_username: jentx123@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
